# Generated by Django 4.2.4 on 2023-09-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='contactno',
            new_name='number',
        ),
    ]
