# Generated by Django 4.2.4 on 2023-10-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0002_rename_contactno_enquiry_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coarses',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('coarse', models.CharField(max_length=100)),
            ],
        ),
    ]
