# Generated by Django 4.2.4 on 2023-10-03 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0004_remove_coarses_coarse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coarses',
        ),
    ]
