# Generated by Django 4.2.4 on 2023-09-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='Notification',
            new_name='notification',
        ),
    ]
