# Generated by Django 4.2.4 on 2023-10-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_rename_notification_notification_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coarses',
            fields=[
                ('id_s', models.AutoField(primary_key=True, serialize=False)),
                ('coarse', models.CharField(max_length=100)),
            ],
        ),
    ]
