# Generated by Django 4.2.4 on 2023-10-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_coarses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centers',
            fields=[
                ('id_s', models.AutoField(primary_key=True, serialize=False)),
                ('center', models.CharField(max_length=200)),
            ],
        ),
    ]
