# Generated by Django 4.2.4 on 2023-10-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_centers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coarses',
            old_name='id_s',
            new_name='id_s1',
        ),
    ]
